catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='book_list'),
    path('book/<int:pk>/', views.BookDetailView.as_view(), name='book_detail'),
    path('authors/', views.AuthorListView.as_view(), name='author_list'),
    path('author/<int:pk>/', views.AuthorDetailView.as_view(), name='author_detail'),
]



locallibrary/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

catalog/models.py
from django.db import models
from django.urls import reverse  # Used to generate URLs by reversing the URL patterns
import uuid  # Required for unique book instances


class Genre(models.Model):
    """Model representing a book genre."""
    name = models.CharField(max_length=200, help_text="Enter a book genre (e.g. Science Fiction)")

    def __str__(self):
        """String for representing the Model object."""
        return self.name


class Author(models.Model):
    """Model representing an author."""
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        """Returns the URL to access a particular author instance."""
        return reverse('author_detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.last_name}, {self.first_name}'


class Book(models.Model):
    """Model representing a book (but not a specific copy of a book)."""
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.RESTRICT, null=True)
    summary = models.TextField(max_length=1000, help_text="Enter a brief description of the book")
    isbn = models.CharField('ISBN', max_length=13, unique=True, help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    genre = models.ManyToManyField(Genre, help_text="Select a genre for this book")

    def __str__(self):
        """String for representing the Model object."""
        return self.title

    def get_absolute_url(self):
        """Returns the URL to access a detail record for this book."""
        return reverse('book_detail', args=[str(self.id)])


class BookInstance(models.Model):
    """Model representing a specific copy of a book (i.e. that can be borrowed from the library)."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="Unique ID for this particular book across whole library")
    book = models.ForeignKey('Book', on_delete=models.RESTRICT, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )
    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m',
        help_text='Book availability',
    )

    class Meta:
        ordering = ['due_back']

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.id} ({self.book.title})'


catalog/views.py
from .models import Book, Author, BookInstance, Genre
from django.shortcuts import render
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin


def index(request):
    """View function for home page of site."""
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()

    # Available books (status = 'a')
    num_instances_available = (
        BookInstance.objects.filter(status__exact='a').count())

    # The 'all()' is implied by default.
    num_authors = Author.objects.count()

    # Number of visits to this view, as counted in the session variable.
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    context = {
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_authors': num_authors,
        'num_visits': num_visits,
    }

    # Render the HTML template index.html with the data in the context variable
    return render(request, 'index.html', context=context)


class BookListView(LoginRequiredMixin, generic.ListView):
    model = Book


class BookDetailView(LoginRequiredMixin, generic.DetailView):
    model = Book

class AuthorListView(LoginRequiredMixin, generic.ListView):
    model = Author

class AuthorDetailView(LoginRequiredMixin, generic.DetailView):
    """View for providing the details of an author. Only accessible to logged-in users."""
    model = Author

catalog/templates/base.html
<!doctype html>
<html lang="en">
{% load static %}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Local Library{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="{% static 'css/my-styles.css' %}" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtOiGRa2b1zG6WsMKQe8ynJ9/5y59bG60flarkev7cmDa6j6D" crossorigin="anonymous"></script>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'index' %}">Local Library</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'index' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'book_list' %}">All Books</a>
                    </li>
                    <!-- Update this line below with the correct url -->
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'author_list' %}">All Authors</a>
                    </li>
                </ul>
            </div>
            <ul class="nav navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    <li>
                        <form action="{% url 'logout' %}" method="post">
                            {% csrf_token %}
                            <button type="submit">Log out</button>
                        </form>
                    </li>
                {% else %}
                    <li>
                        <a class="nav-link" href="{% url 'login' %}">
                            <span class="glyphicon glyphicon-log-in"></span>Login
                        </a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <div class="container">
        <br/>
        {% block content %}
        {% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-7w6qpPDKbXo30Jg1S5gee2prx5mxQ1GZA4CNU+zbETYdRzgziwvhTB7kFTcKVNI" crossorigin="anonymous"></script>
</body>

</html>

catalog/templates/catalog/author_detail.html
{% extends 'base.html' %}

{% block content %}
  <h1>Author Details</h1>
  <p><strong>Name:</strong> {{ author.first_name }} {{ author.last_name }}</p>
  <p><strong>Date of Birth:</strong> {{ author.date_of_birth|date:"Y-m-d" }}</p>
  {% if author.date_of_death %}
    <p><strong>Date of Death:</strong> {{ author.date_of_death|date:"Y-m-d" }}</p>
  {% else %}
    <p>This author is still alive.</p>
  {% endif %}

  <h2>Books by this Author</h2>
  <ul>
    {% for book in author.book_set.all %}
      <li>
        <a href="{% url 'book_detail' book.pk %}">{{ book.title }}</a>
      </li>
    {% empty %}
      <li>No books found.</li>
    {% endfor %}
  </ul>
{% endblock %}


catalog/templates/catalog/author_list.html
{% extends 'base.html' %}

{% block content %}
  <h1>Author List</h1>
  <ul>
    {% for author in author_list %}
      <li>
        <a href="{% url 'author_detail' author.pk %}">{{ author.first_name }} {{ author.last_name }}</a>
      </li>
    {% empty %}
      <p>No authors found.</p>
    {% endfor %}
  </ul>
{% endblock %}

catalog/templates/catalog/book_detail.html
{% extends "base.html" %}

{% block content %}
    <h1>Title: {{ book.title }}</h1>

    <!-- Update the href attribute to link to the author_detail page -->
    <p><strong>Author:</strong> <a href="{% url 'author_detail' book.author.pk %}">{{ book.author }}</a></p>
    <p><strong>Summary:</strong> {{ book.summary }}</p>
    <p><strong>ISBN:</strong> {{ book.isbn }}</p>
    <p><strong>Language:</strong> {{ book.language }}</p>
    <p><strong>Genre:</strong> {{ book.genre.all|join:", " }}</p>

    <div style="margin-left:20px;margin-top:20px">
        <h4>Copies:</h4>
        <hr>
        {% for copy in book.bookinstance_set.all %}
            <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
                {{ copy.get_status_display }}
            </p>
            {% if copy.status != 'a' %}
                <p><strong>Due to be returned:</strong> {{ copy.due_back }}</p>
            {% endif %}
            <p><strong>Imprint:</strong> {{ copy.imprint }}</p>
            <p class="text-muted"><strong>Id:</strong> {{ copy.id }}</p>
        {% endfor %}
    </div>
{% endblock %}

catalog/templates/catalog/book_list.html
{% extends "base.html" %}

{% block content %}
    <h1>Book List</h1>
    {% if book_list %}
        <ul>
            {% for book in book_list %}
                <li>
                    <a href="{{ book.get_absolute_url }}">{{ book.title }}</a>
                    ({{book.author}})
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>There are no books in the library.</p>
    {% endif %}
{% endblock %}

catalog/templates/index.html
{% extends 'base.html' %}

{% block content %}
    <h1>Local Library Home</h1>
    <p>The library has the following books and authors:</p>
    <ul>
        <li><strong>Books:</strong> {{ num_books }}</li>
        <li><strong>Copies:</strong> {{ num_instances }}</li>
        <li><strong>Copies available:</strong> {{ num_instances_available }}</li>
        <li><strong>Authors:</strong> {{ num_authors }}</li>
    </ul>
        <p>You have visited this page {{ num_visits }} time{{num_visits|pluralize }}.</p>
{% endblock %}